### ISSUE TITLE
Moderator abilities with the bots

### ISSUE THREAD

**Issue by Ztech01** [DoublePlusGood23/FriendBot#12]
Abilities include
- Blacklisting
- Removing phrases
- Only one moderator
- Regenerating token for the single moderator
- Ability to have a mod check a new phrase before allowing

**Comment by Ztech01** [comment]
Ability to have a mod check a new phrase before allowing

**Comment by DoublePlusGood23** [comment]
Sounds Good, I especially like the mod whitelisting. :+1:

**Comment by Ztech01** [comment]
The bots for v.2 will have some basic moderator capabilities for now. Later I will implement blacklisting.
