### ISSUE TITLE
Implicit commands

### ISSUE THREAD

**Issue by DoublePlusGood23** [DoublePlusGood23/FriendBot#3]
Ability to have the bots carry on conversations. This isn't possible with the Telegram API, however we may be able to have the bots interact server-side.

**Comment by DoublePlusGood23** [comment]
Can you clarify what you mean here? 

I thought "Implicit Commands" were more User => Bot NLP stuff, not Bot => Bot

**Comment by Ztech01** [comment]
Question: Are the bot able to see the responses from other bots?
Otherwise implicit command are for bot users and bots, the bots can call commands to other bots and user should be able to call the bots without needing to use '/' all the time

**Comment by DoublePlusGood23** [comment]
No telegram specifically made it so Bot2Bot communication isn't possible. I feel the / is good to keep the chat more organized.

**Comment by DoublePlusGood23** [comment]
See [here](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots) for more info.

**Comment by Ztech01** [comment]
Ok, I guess for bot2bot I'll make some server side thing to solve this
