### ISSUE TITLE
Ability to create persona db if none available

### ISSUE THREAD

**Issue by Ztech01** [DoublePlusGood23/FriendBot#7]
This is to allow the ability for the persona to create it's own db file if none are available. This is going to probably add a new attribute, name of bot. This would also allow the DB_PATH to be a path to a folder instead of a file allowing it to be usable on multiple bot instances.

**Comment by Ztech01** [comment]
With the fixing up of the persona file in #9 , I think instead of having a db_path we should use the current directory the python file is in, then it goes into the persona folder and based on which bot name that is given, it either creates a new persona file or opens up an existing one.

**Comment by DoublePlusGood23** [comment]
Ok. Say just a `FRIEND` variable?

**Comment by DoublePlusGood23** [comment]
This would be helpful to since you could just do a `docker run ...` and not need to `docker build ...` or even clone the git rep.
