### ISSUE TITLE
Improving the persona file

### ISSUE THREAD

**Issue by DoublePlusGood23** [DoublePlusGood23/FriendBot#9]
Using simple newline parsing is very simple, but I can't imagine it's particularly efficient (somebody should run some tests), likely doesn't scale well and isn't very dynamic. It would be worth looking into alternatives.

**Comment by Ztech01** [comment]
Maybe, it should be a JSON file that also contains information like api key, phrase, phrase_quip  which would make deploying multiple bots much more seamless.

**Comment by DoublePlusGood23** [comment]
Agreed. :+1:

**Comment by Ztech01** [comment]
I think this is a good template for the persona file. 

{  
    "attributes":{  
        "bot_name":"Ethan",
        "api_key":"123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZAaBbCcDdEe",
        "phrase":"test",
        "phrase_quip":[  
            "Thanks.",
            "Ok then.",
            "New phrase added."
        ]
    },
    "phrases":[  
        "Nice weather we are having.",
        "How are you?",
        "That's cool."
    ]
}

**Comment by DoublePlusGood23** [comment]
Looks good. Simple and concise. :100:
